# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Benedikt Blumenstiel"
description: > # this means to ignore newlines until "email:"
   Intern at AI for Climate Impact | IBM Research | Based in Zurich

email: benedikt.blumenstiel@live.com
#blog logo
logo: "/assets/images/profile.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpg"
# cover: "/assets/images/background_color.png"

name: 'Benedikt Blumenstiel'
author: 'Benedikt Blumenstiel'
author_image: "/assets/images/profile.jpeg"

paginate:	5

url: "blumenstiel.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
# twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/blumenstiel
    desc:	GitHub
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://github.com/blumenstiel
    desc:	LinkedIn
    share_url:
    share_title:
    share_link:

  - icon:	scholar
    url:	https://github.com/blumenstiel
    desc:	Google Scholar
    share_url:
    share_title:
    share_link: