# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Benedikt Blumenstiel"
description: > # this means to ignore newlines until "email:"
   Geospatial AI, IBM Research | Based in Zurich

email: benedikt.blumenstiel@gmail.com
#blog logo
logo: "/assets/images/profile.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpg"
#cover: "/assets/images/background_color.png"

name: 'Benedikt Blumenstiel'
author: 'Benedikt Blumenstiel'
author_image: "/assets/images/profile.jpg"

paginate:	5

url: "blumenstiel.github.io" # the base hostname & protocol for your site
baseurl: ""

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:

  - icon:	github
    url:	https://github.com/blumenstiel
    desc:	GitHub
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/blumenstiel/
    desc:	LinkedIn
    share_url:
    share_title:
    share_link:

  - icon:	google
    url:	https://scholar.google.com/citations?user=sChSEKwAAAAJ&hl=de
    desc:	Google Scholar
    share_url:
    share_title:
    share_link:


# Resume
aboutme:
  - Hello everyone! I'm Benedikt — an open-minded researcher passionate about machine learning, innovation, and sustainability. I work in the AI for Climate Impact Team at the IBM Research Zurich lab. We build multi-modal foundation models for Earth observation and work on climate-related applications using satellite data.
  - Looking forward to connecting with you!
#  - Eager to share ideas and experiences in the intersection of machine learning and geospatial data.

selected:
  - title: TerraMind
    text: "TerraMind is the first multimodal any-to-any generative foundation model for Earth Observation jointly developed by IBM and ESA. TerraMind uses a dual-scale transformer-based encoder-decoder architecture, simultaneously processing pixel-level and token-level data. The model was pre-trained on 500B tokens from 9M spatio-temporally aligned multimodal samples from the TerraMesh dataset and is available on <a href=https://huggingface.co/ibm-esa-geospatial>HuggingFace</a>."
    url: https://huggingface.co/ibm-esa-geospatial
  - title: TerraTorch
    text: "<a href=https://terrastackai.github.io/terratorch/stable/>TerraTorch</a> is an open-source toolkit for fine-tuning geospatial foundation models. Built on PyTorch Lightning and TorchGeo, it provides a modular framework for working with state-of-the-art models like Prithvi, TerraMind, and Clay. With ready-to-use tasks for segmentation, classification, and regression, TerraTorch makes it easy to develop and deploy geospatial AI applications—from research prototypes to enterprise solutions."
    url: https://terrastackai.github.io/terratorch/stable/
  - title: Prithvi EO 2.0
    text: "Prithvi-EO-2.0 is the second generation EO foundation model jointly developed by IBM and NASA. Prithvi-EO-2.0 is based on the ViT architecture, pretrained using a masked autoencoder (MAE) approach with two modifications: 3D positional embeddings for multi-temporal input and additional location and temporal embeddings to encode metadata. The models are pre-trained on 4.2M time series samples and released on <a href=https://huggingface.co/ibm-nasa-geospatial/Prithvi-EO-2.0-300M-TL>HuggingFace</a>."
    url: https://huggingface.co/ibm-nasa-geospatial/Prithvi-EO-2.0-300M-TL
  - title: MESS Benchmark
    text: "Holistic benchmarks allow a robust quantitative comparison of model architectures. However, such evaluation practice covering a wide range of real-world applications is lacking for multi-modal (i.e., text-to-image) zero-shot semantic segmentation tasks. Thus, our motivation to compose the <b>Multi-domain Evaluation of Semantic Segmentation (MESS)</b> benchmark, which consists of 22 datasets for varying application domains. More details can be found on our <a href=https://blumenstiel.github.io/mess-benchmark>website</a>."
    url: https://blumenstiel.github.io/mess-benchmark/
#  - title: Remote Sensing Image Retrieval
#    text: "Embeddings of Geospatial Foundation Models (GeoFMs) enable simple but accurate content-based image retrieval of remote sensing images. We tested the GeoFM Prithvi (IBM-NASA) on two challenging datasets with multi-spectral satellite images and outperformed common computer vision models by a large margin. Check out our <a href=https://github.com/IBM/remote-sensing-image-retrieval>repository</a> for more details."
#    url: https://github.com/IBM/remote-sensing-image-retrieval
#  - title: CLAIMED Component Compiler (C3)
#    text: "The <a href=https://claimed-framework.github.io>CLAIMED</a> framework enables rapid development and deployment of processing steps, e.g. for data preprocessing in deep learning. Using the CLAIMED Component Compiler (C3), components can be easily built from a Python script or notebook and deployed on KubeFlow, Kubernetes, or locally via CLI. Notably, C3 eliminates the need for Docker or Kubernetes expertise, making it accessible to any data scientist to deploy code on clusters. Check out the <a href=https://github.com/claimed-framework/c3/blob/main/GettingStarted.md>Getting Started</a> page for more information."
#    url: https://github.com/claimed-framework/c3/blob/main/GettingStarted.md

projects:
  - Multi-modal foundation models and vision language models for Earth observation (<a href=https://fast-eo.webflow.io>FAST-EO</a>)
  - Generalization benchmark for Zero-Shot Semantic Segmentation evaluating models like OVSeg or SAM on domain-specific downstream tasks (Master’s thesis)
  - Object detection in construction plans using Faster-RCNN and Tensorflow
  - Extremity X-ray image classification with Vision Transformers using PyTorch
  - Electricity grid load forecasting with AutoML frameworks including NeuralProphet and Vertex AI
  - Topic modeling of scientific paper using nltk and genism (Bachelor’s thesis)

work:
  - title: Research Software Engineer, AI for Climate Impact, IBM Research
    time: 02/2024 - present
    tasks:
      - Built TerraMind, the leading EO foundation model on PANGAEA benchmark, using multimodal token prediction
      - Enabled large-scale EO pre-training and improved wildfire and flooding fine-tuning by curating multimodal datasets (TerraMesh, ImpactMesh)
      - Developed MS-CLIP, a multispectral vision-language EO model, with 7 pp. accuracy gains compared to RGB-only models using MLLM-generated captions
      - Applied EO embeddings from Prithvi to remote sensing image retrieval, outperforming general computer vision models by 6 pp. mAP
      - Increased external adoption to 500k+ model downloads by open-sourcing the TerraMind and Prithvi models, integrating them in a easy-to-use manner into the TerraTorch package, and promoting them through talks and webinars

  - title: Intern, AI for Climate Impact, IBM Research
    time: 08/2023 - 02/2024
    tasks:
      - Curated a 4.2M time series dataset for the Prithvi 2.0 pre-training, resulting in +8 pp. downstream task performance compared to the previous version, by using diverse sampling strategy based on land-cover and bioregions
      - Developed data pipelines for automated data fetching of missing inputs and faster data loading in the IBM GEO Studio, a low-code GeoAI webapp

  - title: Junior Researcher, Applied AI in Services Lab, KIT
    time: 05/2020 - 04/2022
    tasks:
      - Published insights on human–AI collaboration by studying interactive few-shot learning in computer vision
      - Trained few-shot object detection models for first-of-their-kind AEC applications using TensorFlow

  - title: Design Thinking project, KIT & HUK Coburg
    time: 10/2019 - 06/2020
    tasks:
      - Used design thinking to develop user-centered, digital innovations and prototypes for retirement saving

  - title: Intern, R&D Strategy, AUDI AG
    time: 07/2017 - 02/2018
    tasks:
      - Supported the project manager in defining a new technology-focused R&D strategy
      - Worked in the project management office of an R&D transformation project


education:
  - title: M.Sc. Information Systems, Karlsruhe Institute of Technology
    time: 10/2019 - 04/2023
    text:
      - Focus on machine learning and service innovation
      - Thesis on multi-domain adaptation of zero-shot semantic segmentation

  - title: Exchange, Norwegian University of Science and Technology
    time: 01/2021 - 06/2021
    text:
      - Courses in computer vision, natural language processing and statistics

  - title: B.Sc. Industrial Engineering, Karlsruhe Institute of Technology
    time: 10/2015 - 09/2019
    text:
      - Focus on digital services and business strategy
      - Thesis on large-scale topic modeling of scientific papers using NLP

publications:
  - text: "Basile, G.*, Jakubik, J.*, Blumenstiel, B., Brunschwiler, T., & Moreno, J. B. (2025). Quantizing Space and Time: Fusing Time Series and Images for Earth Observation. <i>arXiv preprint arXiv:2510.23118</i>."
    url: "https://arxiv.org/abs/2510.23118"
  - text: "Costa Watanabe, J.*, Wittmann, I.*, Blumenstiel, B., & Schindler, K. (2025). TerraCodec: Compressing Earth Observations. <i>arXiv preprint arXiv:2510.12670</i>."
    url: "https://arxiv.org/abs/2510.12670"
  - text: "Jakubik, J.*, Yang, F.*, Blumenstiel, B.*, Scheurer, E., Sedona, R., Maurogiovanni, S. et al. (2025). TerraMind: Large-Scale Generative Multimodality for Earth Observation. <i>IEEE/CVF International Conference on Computer Vision.</i>"
    url: "https://arxiv.org/abs/2504.11171"
  - text: "Blumenstiel, B., Fraccaro, P., Marsocci, V., Jakubik, J., Maurogiovanni, S., Czerkawski, M. et al. (2025). TerraMesh: A Planetary Mosaic of Multimodal Earth Observation Data. In <i>Proceedings of the Computer Vision and Pattern Recognition Conference (CVPR) Workshops.</i>"
    url: "https://arxiv.org/abs/2503.15969"
  - text: "Marti Escofet, F.*, Blumenstiel, B.*, Scheibenreif, L., Fraccaro, P., and Schindler, K. (2025). Fine-tune Smarter, Not Harder: Parameter-Efficient Fine-Tuning for Geospatial Foundation Models. In <i>Joint European Conference on Machine Learning and Knowledge Discovery in Databases (ECML) (pp. 359-375).</i>"
    url: "https://arxiv.org/abs/2504.17397"
  - text: "Marimo, C. T.*, Blumenstiel, B.*, Nitsche, M., Jakubik, J., & Brunschwiler, T. (2025). Beyond the Visible: Multispectral Vision-Language Learning for Earth Observation. In <i>Joint European Conference on Machine Learning and Knowledge Discovery in Databases (ECML) (pp. 516-532).</i>"
    url: "https://arxiv.org/abs/2503.15969"
  - text: "Blumenstiel, B., Braham, N. A. A., Albrecht, C. M., Maurogiovanni, S., & Fraccaro, P. (2025). Ssl4eo-s12 v1. 1: A multimodal, multiseasonal dataset for pretraining, updated. <i>arXiv preprint arXiv:2503.00168.</i>"
    url: "https://arxiv.org/abs/2503.00168"
  - text: "Gomes, C., Blumenstiel, B., Almeida, J. L. D. S., de Oliveira, P. H., Fraccaro, P., Marti Escofet, F. et al. (2025). TerraTorch: The Geospatial Foundation Models Toolkit. In <i>Proceedings of the IEEE International Geoscience and Remote Sensing Symposium (IGARSS).</i>"
    url: "https://arxiv.org/abs/2503.20563"
  - text: "Szwarcman, D.*, Roy, S.*, Fraccaro, P.*, Gíslason, Þ. E., Blumenstiel, B., Ghosal, R., ... & Moreno, J. B. (2024). Prithvi-EO-2.0: A Versatile Multi-Temporal Foundation Model for Earth Observation Applications. In <i>IEEE Transactions on Geoscience and Remote Sensing.</i>"
    url: "https://arxiv.org/abs/2412.02732"
  - text: "Blumenstiel, B., Moor, V., Kienzler, R., Brunschwiler, T. (2024). Multi-Spectral Remote Sensing Image Retrieval using Geospatial Foundation Models. In <i>Proceedings of the IEEE International Geoscience and Remote Sensing Symposium (IGARSS).</i>"
    url: "https://arxiv.org/abs/2403.02059"
  - text: "Blumenstiel, B.*, Jakubik, J.*, Kühne, H., & Vössing, M. (2023). What a MESS: Multi-Domain Evaluation of Zero-Shot Semantic Segmentation. In <i>Advances in Neural Information Processing Systems.</i>"
    url: "https://arxiv.org/abs/2306.15521"
  - text: "Kienzler, R., Tizzei, L. P. T., Blumenstiel, B., Nagy, Z. A., Mukkavilli, S. K., Schmude, J., Freitag, M., Behrendt, M., Civitarese, D. S., Simumba, N., Kimura, D.  & Hamann, H. (2023). TensorBank: Tensor Lakehouse for Foundation Model Training. In <i>IEEE International Conference on Big Data (BigData).</i>"
    url: "https://arxiv.org/abs/2309.02094"
  - text: "Jakubik, J., Hemmer, P., Voessing, M., Blumenstiel, B., Bartos, A., & Mohr, K. (2022). Designing a Human-in-the-Loop System for Object Detection in Floor Plans. In <i>Proceedings of the AAAI Conference on Artificial Intelligence.</i>"
    url: "https://ojs.aaai.org/index.php/AAAI/article/view/21522"
  - text: "Jakubik, J., Blumenstiel, B., Voessing, M., & Hemmer, P. (2022). Instance Selection Mechanisms for Human-in-the-Loop Systems in Few-Shot Learning. In <i>Wirtschaftsinformatik 2022 Proceedings.</i>"
    url: "https://arxiv.org/abs/2207.06835"

others:
  programming: Python, PyTorch, HPC, Kubernetes, Docker, R, Java, Lightning, TensorFlow, GeoPandas, Xarray, Rasterio, Numpy, Pandas
  skills: English, German, deep learning, computer vision, data processing, geospatial data, project management, PowerPoint, design thinking
  awards: 2025 AGU Open Science Recognition Prize, NASA Agency Group Award 2025, and IBM Outstanding Research Accomplishment for the TerraMind and Prithvi foundation models
  certifications: Data Science Profession Certification - Experienced, issued by IBM; Technical Collaboration Achievement Program (TCAP) award from IBM for open-source contributions to geospatial foundation models

talks:
  - Keynote on "TerraMind", ESA-NASA International Workshop on AI Foundation Model for EO (video: https://youtu.be/6P4Hs8dWeBk?si=IzQlZOZxnfrAlW71&t=1992)
  - Invited Talk "AI to Accelerate the Energy Transition and Adapt to Climate Change", AMLD 2025
  - Invited Talk "Transforming Geospatial Analysis with Foundation Models", AMLD 2024 (https://youtu.be/QdLMTkyBZJk?si=-0In9dA4vm-JxAFI)
  - Several workshops on Geospatial Foundation Models at ETH Summer School 2025, ESA-NASA workshop 2025, AMLD 2025
  - Co-organizer of the REO Workshop at NeurIPS 2026 (https://reo-workshop.org/2026/)

awards:
  - 2025 AGU Open Science Recognition Prize for the Prithvi-Geospatial AI Foundation Model Team
  - NASA Agency Group Award for Prithvi-EO
  - IBM Outstanding research accomplishment for "From NASA to ESA and Beyond – Scaling IBM’s Leadership in AI for Science through Strategic Partnerships" as one of the developers of the TerraMind model
  - IBM Research accomplishment for “Improvement and application of CLAIMED workflow and operator framework in IBM products” as the main contributor for the CLAIMED Component Compiler (C3)
  - Received a Technical Collaboration Achievement Program (TCAP) award from IBM for open-source contributions to geospatial foundation models
  - Data Science Profession Certification - Experienced, issued by IBM

