# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Benedikt Blumenstiel"
description: > # this means to ignore newlines until "email:"
   AI for Climate Impact, IBM Research | Based in Zurich

email: benedikt.blumenstiel@live.com
#blog logo
logo: "/assets/images/profile.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpg"
# cover: "/assets/images/background_color.png"

name: 'Benedikt Blumenstiel'
author: 'Benedikt Blumenstiel'
author_image: "/assets/images/profile.jpeg"

paginate:	5

url: "blumenstiel.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@beneblumenstiel'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:

  - icon:	github
    url:	https://github.com/blumenstiel
    desc:	GitHub
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/blumenstiel/
    desc:	LinkedIn
    share_url:
    share_title:
    share_link:

  - icon:	google
    url:	https://scholar.google.com/citations?user=UGynAs4AAAAJ&hl=de
    desc:	Google Scholar
    share_url:
    share_title:
    share_link:

#  - icon:	twitter
#    url:	https://twitter.com/beneblumenstiel
#    desc:   Twitter
#    share_url:
#    share_title:
#    share_link:


# Resume
aboutme:
  - Hello everyone! I'm Benedikt — an open-minded researcher passionate about machine learning, innovation, and sustainability. I work in the AI for Climate Impact Team at the IBM Research Zurich lab. We build foundation models for earth observation and work on climate-related applications using satellite data. Eager to share ideas and experiences in the intersection of machine learning and sustainability.
  - Looking forward to connecting with you!

selected:
  - title: Remote Sensing Image Retrieval
    text: Embeddings of Geospatial Foundation Models (GeoFMs) enable simple but accurate content-based image retrieval of remote sensing images. We tested the GeoFM Prithvi (IBM-NASA) on two challenging datasets with multi-spectral satellite images and outperformed common computer vision models by a large margin. Check out our <a href=https://github.com/IBM/remote-sensing-image-retrieval>repository</a> for more details.
    url: https://github.com/IBM/remote-sensing-image-retrieval
  - title: MESS Benchmark
    text: Holistic benchmarks allow a robust quantitative comparison of model architectures. However, such evaluation practice covering a wide range of real-world applications is lacking for multi-modal (i.e., text-to-image) zero-shot semantic segmentation tasks. Thus, our motivation to compose the <b>Multi-domain Evaluation of Semantic Segmentation (MESS)</b> benchmark, which consists of 22 datasets for varying application domains. More details can be found on our <a href=https://blumenstiel.github.io/mess-benchmark>website</a>.
    url: https://blumenstiel.github.io/mess-benchmark/
  - title: CLAIMED Component Compiler (C3)
    text: The <a href=https://claimed-framework.github.io>CLAIMED</a> framework enables rapid development and deployment of processing steps, e.g. for data preprocessing in deep learning. Using the CLAIMED Component Compiler (C3), components can be easily built from a Python script or notebook and deployed on KubeFlow, Kubernetes, or locally via CLI. Notably, C3 eliminates the need for Docker or Kubernetes expertise, making it accessible to any data scientist to deploy code on clusters. Check out the <a href=https://github.com/claimed-framework/c3/blob/main/GettingStarted.md>Getting Started</a> page for more information.
    url: https://github.com/claimed-framework/c3/blob/main/GettingStarted.md

projects:
  - Multi-modal foundation models for earth observation (<a href=https://fast-eo.webflow.io>FAST-EO</a>)
  - Generalization benchmark for Zero-Shot Semantic Segmentation evaluating models like OVSeg or SAM on domain-specific downstream tasks (Master’s thesis)
  - Object detection in construction plans using Faster-RCNN and Tensorflow
  - Extremity X-ray image classification with Vision Transformers using PyTorch
  - Electricity grid load forecasting with AutoML frameworks including NeuralProphet and Vertex AI
  - Topic modeling of scientific paper using nltk and genism (Bachelor’s thesis)

work:
  - title: Research Scientist, AI for Climate Impact, IBM Research
    time: 02/2024 - present
    tasks:
      - Research on pre-training of multi-satellite and multi-modal geospatial foundation models
      - Developing the data pipeline for a geospatial ML platform and foundation model pre-training

  - title: Intern, AI for Climate Impact, IBM Research
    time: 08/2023 - 02/2024
    tasks:
      - Deploying and applying MLOps tools and pipelines
      - Developing the CLAIMED Component Compiler (C3) for the CLAIMED project
      - Experiments with remote sensing image retrieval using geospatial foundation models

  - title: Junior Researcher, Applied AI in Services Lab, KIT
    time: 05/2020 - 04/2022
    tasks:
      - Research about human-AI collaboration and machine learning, with a focus on few-shot learning
      - Developed AI applications for a AI project in the AEC industry
      - Worked with multiple computer vision models and deployed them on high performance clusters

  - title: Design Thinking project, KIT & HUK Coburg
    time: 10/2019 - 06/2020
    tasks:
      - Used design thinking to develop user-centered innovations and prototypes for retirement saving

  - title: Intern, R&D Strategy, AUDI AG
    time: 07/2017 - 02/2018
    tasks:
      - Supported the project manager in defining a new technology-focused R&D strategy
      - Worked in the project management office of an R&D transformation project


education:
  - title: M.Sc. Information Systems, Karlsruhe Institute of Technology
    time: 10/2019 - 04/2023
    text:
      - Focus on machine learning and service innovation

  - title: Exchange, Norwegian University of Science and Technology
    time: 01/2021 - 06/2021
    text:
      - Courses in computer vision, natural language processing and statistics

  - title: B.Sc. Industrial Engineering, Karlsruhe Institute of Technology
    time: 10/2015 - 09/2019
    text:
      - Focus on digital services and business strategy

publications:
  - text: "Blumenstiel, B., Moor, V., Kienzler, R., Brunschwiler, T. (2024). Multi-Spectral Remote Sensing Image Retrieval using Geospatial Foundation Models. <i>Proceedings of the IEEE International Geoscience and Remote Sensing Symposium (IGARSS).</i>"
    url: "https://arxiv.org/abs/2403.02059"
  - text: "Blumenstiel, B., Jakubik, J., Kühne, H., & Vössing, M. (2023). What a MESS: Multi-Domain Evaluation of Zero-Shot Semantic Segmentation. <i>Advances in Neural Information Processing Systems.</i>"
    url: "https://arxiv.org/abs/2306.15521"
  - text: "Kienzler, R., Blumenstiel, B., Nagy, Z. A., Mukkavilli, S. K., Schmude, J., Freitag, M., Behrendt, M., Civitarese, D. S.  & Hamann, H. (2023). TensorBank: Tensor Lakehouse for Foundation Model Training. <i>IEEE International Conference on Big Data.</i>"
    url: "https://arxiv.org/abs/2309.02094"
  - text: "Jakubik, J., Hemmer, P., Voessing, M., Blumenstiel, B., Bartos, A., & Mohr, K. (2022). Designing a Human-in-the-Loop System for Object Detection in Floor Plans. <i>Proceedings of the AAAI Conference on Artificial Intelligence.</i>"
    url: "https://ojs.aaai.org/index.php/AAAI/article/view/21522"
  - text: "Jakubik, J., Blumenstiel, B., Voessing, M., & Hemmer, P. (2022). Instance Selection Mechanisms for Human-in-the-Loop Systems in Few-Shot Learning. <i>International Conference on Wirtschaftsinformatik.</i>"
    url: "https://arxiv.org/abs/2207.06835"

skills:
  advanced: Python, Deep Learning, Computer Vision, Data processing, German, English, PowerPoint, Design Thinking
  basic: Docker, Kubernetes, Kubeflow, OpenShift, Travis CI, R
